version: '3'

services:
    clone-netflix-db:
        container_name: "clone-netflix-db"
        image: "postgres"
        environment:
          - POSTGRES_USER=netflix
          - POSTGRES_PASSWORD=netflix
          - POSTGRES_DB=Netflix
          - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
          - "5432:5432"
        volumes:
          - "./database/data/:/var/lib/postgresql/data"
    